name: dev-benches

services:
  cpp-bench:
    env_file: ../.env
    image: cpp-bench:${USER:-brett}
    container_name: cpp-bench
    command: sleep infinity
    working_dir: /workspace
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ulimits:
      core: -1
    environment:
      - VCPKG_ROOT=/opt/vcpkg
      - CC=/usr/bin/gcc-12
      - CXX=/usr/bin/g++-12
