name: dev-benches

services:
  java-bench:
    env_file: ../.env
    image: java-bench:${USER:-brett}
    container_name: java-bench
    command: sleep infinity
    working_dir: ${WORKING_DIR:-/workspace}
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      - GRADLE_HOME=/opt/gradle/gradle-8.5
      - MAVEN_OPTS=-Dmaven.repo.local=/workspace/m2repo
    tty: true
