name: sys-benches

services:
  cloud-bench:
    image: cloud-bench:${USER:-brett}
    container_name: cloud-bench
    command: sleep infinity
    volumes:
      # Mount full host home directory
      - ~:/home/${USER:-brett}:cached
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    environment:
      - USER=${USER:-brett}
      - DOCKER_HOST=unix:///var/run/docker.sock
    privileged: true
    network_mode: host
